<h1>Python: without numpy or sklearn </h1>




<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [31]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    res_matrix = [[0 for m in range(len(B[0]))] for n in range(len(A))] #creates an m x n matrix with zeros as initial values
    if len(A[0])==len(B):# the number of columns in the first matrix must be equal to the number of rows in the second matrix.
        
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(B)):
                    res_matrix[i][j] += A[i][k]*B[k][j]
        for res in res_matrix:
            print(res)
    else :
        print("Not possible")
A = [[1,3,4],
     [2,5,7],
     [5,9,6]]
B = [[1,0,0],
     [0,1,0],
     [0,0,1]]
    
matrix_mul(A, B)

[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


In [23]:
X   = [[1,2],
       [3,4]]
Y   = [[1,4],
        [5,6],
        [7,8],
        [9,6]]
matrix_mul(X, Y)

Not possible


In [33]:
res_matrix = [[0 for m in range(len(p[0]))] for n in range(len(o))]

o  = [[1,2],
       [3,4]]
p  = [[1,2,3,4,5],
       [5,6,7,8,9]]
print(res_matrix)
matrix_mul(o,p)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [95]:
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure
def pick_a_number_from_list(A):
# your code here for picking an element from with the probability propotional to its magnitude
    sum_of_A = sum(A) # Step1:(a) To find the sum of all the elements of list A 
    A_norm=[] # An empty list is created to store normalised values
    for num in A:
        A_norm.append(num/(sum_of_A)) # (b)Each element is normalised by the elements with its sum
    cum_sum=[] # An empty list is created to store cumulative sumed values
    val = 0
    for k in range(len(A)):
        val+=A_norm[k]
        cum_sum.append(val) #(c) All the values are appended in cum_sum as cumulative sum values
        
    r = random.uniform(0.0,1.0) # step2: a random number is picked between 0.0 to 1.0

    for i in range(len(cum_sum)):
            if(r<=cum_sum[i]): # step3: that number is compared with the cum_sum values and 
                number=A[i] # the number is equated with the values of A at index i
                break
    return number

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A) #above function is called to select random number
        print(number)
A = [0,5,27,6,13,28,100,45,10,79]
sampling_based_on_magnitued()

28
100
28
27
79
79
6
79
79
79
13
45
100
100
13
28
13
79
79
27
79
6
100
79
79
100
100
27
100
79
100
28
27
45
79
100
45
27
28
100
100
27
79
100
79
100
100
79
28
79
45
27
100
79
13
79
79
45
100
79
13
100
100
100
45
27
45
6
5
100
100
45
100
79
100
79
100
27
28
79
100
79
100
27
100
100
79
100
28
10
28
28
100
79
79
100
100
100
79


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [2]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    for digit in String:
        if re.findall('\d',digit):
            print("#",end="")# modified string which is after replacing the # with digits
      
String1 = input("Enter The String:")
replace_digits(String1)

Enter The String:hguut67757rf8hy
######

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [21]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    
    dict_1 = {students[i]:marks[i] for i in range(len(students))}#Creating dictionary using dictionary Comprehension
    # write code for computing top top 5 students
    sorted_dict_desc = sorted(dict_1, key= dict_1.get,reverse=True)
    x =sorted_dict_desc[:5] # Sorting dictionary values in descending order
    print("a.top 5 students:")
    for j in x:
        print(j,dict_1[j])
    print(" ")
    # write code for computing top least 5 students
    sorted_dict_asc = sorted(dict_1, key= dict_1.get)#Soring students marks in ascending order
    y = sorted_dict_asc[:5]
    print("b.least 5 students:")
    for i in y:
        print(i,dict_1[i])
    print(" ")
    
    #students_within_25_and_75
    sorted_marks_list = sorted(marks)#list is in ascending order so far
    max_marks = sorted_marks_list[-1]#maximum number is stored in max_marks
    min_marks = sorted_marks_list[0]#minimum value is stored 
    diff = max_marks-min_marks
    per_25th = diff*0.25 #25th percentile is determined and stored in per_25th
    per_75th = diff*0.75 #75th percentile is stored in per_75th
    
    print("c.students_within_25_and_75:")
    for k in sorted_dict_asc:
        if dict_1[k]<per_25th or dict_1[k]>per_75th:
            continue
        else:
            print(k,dict_1[k])
    
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
display_dash_board(students, marks)
 




a.top 5 students:
student8 98
student10 80
student2 78
student5 48
student7 47
 
b.least 5 students:
student3 12
student4 14
student9 22
student6 43
student1 45
 
c.students_within_25_and_75:
student9 22
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [43]:
import math as m

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    res = []
    for i in range(len(S)): #𝑐𝑜𝑠^−1((𝑥⋅𝑝+𝑦⋅𝑞)/(√𝑥2+𝑦2)⋅(√𝑝2+𝑞2)) divided into three parts
                            
        num = S[i][0]*P[0]+S[i][1]*P[1] # Numerator of the formula is stored in num
        den = m.sqrt(S[i][0]**2+S[i][1]**2)*m.sqrt(P[0]**2+P[1]**2)# Denominator is stored in den
        dis = m.acos(num/den) # Cos^-1 of num and den is stored in dis
        
        res.append(dis)# Distance between each points is stored in res[]
    
    dict_1 = {S[i]:res[i] for i in range(len(S))}#Comprehension dictionary is created based on S points and res values
    
    sorted_dict = list(sorted(dict_1,key=dict_1.get))[:5] # Created a list and sorted in ascending order and five least values 
                                                        #are stored in sorted_dict
    print("Five closest points(based on cosine distance) in S from P are:\n")
    for pt in sorted_dict:
        print(pt)
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)


Five closest points(based on cosine distance) in S from P are:

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [17]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    for point1 in red: # For points in Red list
        eq1 = line.replace('x','*'+str(point1[0])) # The variables 'x' and 'y' are replaced with (x,y) coordinates respectively
        eq1 = eq1.replace('y','*'+str(point1[1]))
        
        sol1 = eval(eq1) # eval() func is used to parse and evaluate the expression
        if sol1 < 0:
            return "NO" # if the sol1 is less than 0 it returns NO
        
    for point2 in blue: # For points in Blue list
        eq2 = line.replace('x','*'+str(point2[0]))
        eq2 = eq2.replace('y','*'+str(point2[1]))
        sol2 = eval(eq2)
        if sol2 > 0:
            return "NO"  # if the sol2 is greater than 0 it returns NO
    
    return "YES" # if both the above conditions are false then it returns YES

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5","5x-3y-10"]

for line in Lines:
    yes_or_no = i_am_the_one(Red, Blue, line)
    print(yes_or_no) # the returned value

YES
NO
NO
YES
NO


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [31]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    lst=string.split(',')#Here we split the string
    for i in range(len(lst)):# This loop is for finding first digit in list
        if lst[i].isdigit():#At any index value digit is occured 
            for j in range(i+1):
                lst[j]=int(lst[i])//(i+1)
            new_index=i#Wherever the digit is occured that index is stored
            new_value=int(lst[i])#The value will be stored in it
            break
     #This iteration starts from the new index value       
    for i in range(new_index+1,len(lst)):
        if lst[i].isdigit():
            temp=(new_value+int(lst[i]))//(i-new_index+1)#stores the average value if two values occur in list
            for j in range(new_index,i+1):
                lst[j]=temp
            
            new_index=i
            new_value=int(lst[i])
    #this block continues and do the last calculations of list
    try:
        for i in range(new_index+1,len(lst)):
            if not(lst[i].isdigit()):
                count=lst.count('_')#counts the number of '_' we have in a list
                break
        temp1=new_value//(count+1)
        for i in range(new_index,len(lst)):
            lst[i]=temp1
    except:
        pass
    return lst 
S1 = "_,_,_,24"
S2=  "40,_,_,_,60"
S3 = "80,_,_,_,_"
S4 = "_,_,30,_,_,_,50,_,_"
print("Input1:", S1)
print("Output1:",','.join(map(str,curve_smoothing(S1))))
print("\nInput2:",S2)
print("Output2:",','.join(map(str,curve_smoothing(S2))))
print("\nInput3:",S3)
print("Output3:",','.join(map(str,curve_smoothing(S3))))
print("\nInput4:",S4)
print("Output5:",','.join(map(str,curve_smoothing(S4))))

Input1: _,_,_,24
Output1: 6,6,6,6

Input2: 40,_,_,_,60
Output2: 20,20,20,20,20

Input3: 80,_,_,_,_
Output3: 16,16,16,16,16

Input4: _,_,30,_,_,_,50,_,_
Output5: 10,10,12,12,12,12,4,4,4


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    F = set()
    for a in range(len(A)):
        F.add(A[a][0])
    sorted_F = sorted(list(F))#All the unique values of F are stored in sorte_list
    
    count_of_FS = dict()# All the unique combinations  are created and the values of their occurences is counted and stored as dict values
    count_of_S = {'S1':0,'S2':0,'S3':0}
    
    for i in A:#This  loop is find the uniuque combinations as keys and 0 as their values
        x = str(i[0])+str(i[1])
        count_of_FS[x]=0
    
    for j in range(len(A)):#This loop is to determine the counts of various combinations and conditions
        F_Intersection_S = A[j][0]+A[j][1]
        count_of_FS[F_Intersection_S]+=1
        S_val=A[j][1]
        count_of_S[S_val]+=1
    
    res = []#empty list is created to store all the occurances
    for f in sorted_F:
        for s in count_of_S:
            t='P(F={F}|S=={S})={FS}/{s}'.format(F=f,S=s,
                                                    FS = count_of_FS.get((f+s),0),s=count_of_S[s])
            res.append(t)
    return res

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

result = compute_conditional_probabilites(A)

lst = [result[i:i + 3] for i in range(0, len(result), 3)]#making a sublist of 3 elements of main list
o = ['a','b','c','d','e']
for i in range(len(lst)):# Converting list into string
    print(o[i]+'.',', '.join(map(str,lst[i])))
        

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    S3 = S1.split()
    S4 = S2.split()# Convert string in a list using split() function
    a = 0
    b = []
    c = [] # Creating empty lists to add unique words in both strings
   
    for i in range(len(S3)):
        for j in range(len(S4)):
            if S3[i]==S4[j]: # If the word of S3 is equal to S4 increment a by 1
                a+=1
    for x in S3:
        if not x in S4: # If a word present in S3 but not in S4 then append that word into empty list b
            b.append(x)
    for y in S4:
        if not y in S3: # If a word present in S4 but not in S3 then append that word into empty list b
            c.append(y)
    return a, b, c # returns all the three operations
    
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a.",a,"\nb.",b,"\nc.",c,)

#Above task can be done using sets as well
    # m = set(S3)
    #n = set(S4) Using set data type we can perform the same operations
    #print(list(m.difference(n))

a. 7 
b. ['first', 'F', '5'] 
c. ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math as m

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    total = 0
    n = len(A)
    for i in range(n):#𝑓(𝑌,𝑌𝑠𝑐𝑜𝑟𝑒)=−1∗1𝑛Σ𝑓𝑜𝑟𝑒𝑎𝑐ℎ𝑌,𝑌𝑠𝑐𝑜𝑟𝑒𝑝𝑎𝑖𝑟(𝑌𝑙𝑜𝑔10(𝑌𝑠𝑐𝑜𝑟𝑒)+(1−𝑌)𝑙𝑜𝑔10(1−𝑌𝑠𝑐𝑜𝑟𝑒)) this function is divided into three
                      # steps where we 1.calculate loss for each point 
                      #2.then store in a variable total
                      #3.then divide with n(number of rows) and multiply with -1
        
        loss= A[i][0]*m.log10(A[i][1])+(1-A[i][0])*(m.log10(1-A[i][1]))
        total = loss+total
    total_loss = -1/n*(total)
    return total_loss  # returning the total loss for the above function

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print("Loss for the function 𝑓(𝑌,𝑌𝑠𝑐𝑜𝑟𝑒)=−1∗1𝑛Σ𝑓𝑜𝑟𝑒𝑎𝑐ℎ𝑌,𝑌𝑠𝑐𝑜𝑟𝑒𝑝𝑎𝑖𝑟(𝑌𝑙𝑜𝑔10(𝑌𝑠𝑐𝑜𝑟𝑒)+(1−𝑌)𝑙𝑜𝑔10(1−𝑌𝑠𝑐𝑜𝑟𝑒)) is:\n")
print(round(loss,7))

Loss for the function 𝑓(𝑌,𝑌𝑠𝑐𝑜𝑟𝑒)=−1∗1𝑛Σ𝑓𝑜𝑟𝑒𝑎𝑐ℎ𝑌,𝑌𝑠𝑐𝑜𝑟𝑒𝑝𝑎𝑖𝑟(𝑌𝑙𝑜𝑔10(𝑌𝑠𝑐𝑜𝑟𝑒)+(1−𝑌)𝑙𝑜𝑔10(1−𝑌𝑠𝑐𝑜𝑟𝑒)) is:

0.4243099
